package com.demo.upimesh.model;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * The over-the-wire format. This is what hops from phone to phone via Bluetooth.
 *
 * The intermediate phones can read the OUTER fields (packetId, ttl, createdAt)
 * because they need them for routing and dedup. They CANNOT read `ciphertext` —
 * that's encrypted with the server's public key.
 *
 * NOTE on outer-field tampering:
 *   A malicious intermediate could change `packetId` or `createdAt`. That's why
 *   we use the ciphertext's hash (not packetId) as the idempotency key on the
 *   server. The ciphertext is authenticated by hybrid encryption, so any
 *   tampering inside the encrypted blob is detected on decryption.
 *
 * @Data generates getters/setters/equals/hashCode/toString
 * @NoArgsConstructor needed by Jackson for JSON deserialization
 */
@Data
@NoArgsConstructor
@Schema(description = "The over-the-wire packet that hops from phone to phone via Bluetooth Mesh.")
public class MeshPacket {

    @NotBlank
    @Schema(description = "UUID generated by the sender. Used by intermediate phones for gossip deduplication. Can be tampered with by malicious nodes.", example = "a1b2c3d4-5678-90ef-ghij-klmnopqrstuv")
    private String packetId; // UUID, used by intermediates for gossip dedup

    @Min(0)
    @Schema(description = "Hops remaining before the packet is dropped. Decremented by intermediate nodes.", example = "5")
    private int ttl; // Hops remaining; intermediates decrement it

    @NotNull
    @Schema(description = "Epoch milliseconds when the sender created the packet.", example = "1700000000000")
    private Long createdAt; // epoch millis, when sender created the packet

    @NotBlank
    @Schema(description = "The encrypted payload containing the payment instructions. Encrypted with the server's public key using Hybrid Encryption (RSA-OAEP + AES-GCM).", example = "base64_encoded_ciphertext_blob_here")
    private String ciphertext; // base64(RSA-encrypted AES key + AES-GCM ciphertext)
}
