package com.demo.upimesh.service;

/**
 * Immutable snapshot of aggregated mesh and ledger statistics.
 *
 * This record is constructed in the stats API and serialised to JSON.
 * Using a Java Record keeps the DTO concise: all fields are final,
 * equals/hashCode/toString are generated by the compiler.
 *
 * @param totalAccounts        number of accounts in the ledger
 * @param totalTransactions    total settled transaction records
 * @param idempotencyCacheSize live size of the in-memory dedup cache
 * @param activeMeshDevices    how many virtual mesh devices are currently online
 * @param bridgeDeviceCount    how many of those devices have internet access
 */
public record PacketStats(
        long totalAccounts,
        long totalTransactions,
        int  idempotencyCacheSize,
        int  activeMeshDevices,
        long bridgeDeviceCount
) {}
